/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rfid_interface_SerialPort */

#ifndef _Included_rfid_interface_SerialPort
#define _Included_rfid_interface_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rfid_interface_SerialPort
 * Method:    openSerialPort
 * Signature: (Ljava/lang/String;IIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_rfid_1interface_SerialPort_openSerialPort
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     rfid_interface_SerialPort
 * Method:    closeSerialPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rfid_1interface_SerialPort_closeSerialPort
  (JNIEnv *, jobject);

/*
 * Class:     rfid_interface_SerialPort
 * Method:    flushSerialPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rfid_1interface_SerialPort_flushSerialPort
  (JNIEnv *, jobject);

/*
 * Class:     rfid_interface_SerialPort
 * Method:    flushInputSerialPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rfid_1interface_SerialPort_flushInputSerialPort
  (JNIEnv *, jobject);

/*
 * Class:     rfid_interface_SerialPort
 * Method:    flushOutputSerialPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rfid_1interface_SerialPort_flushOutputSerialPort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
